### ISSUE TITLE
Masternode PRE_ENABLED

### ISSUE THREAD

**Issue by StifflersMoM69** [sparkscrypto/Sparks#9]
Hi!

I followd you guid for Masternode Guid public.pdf but Status stays at PRE_ENABLED. When i run venv/bin/python bin/sentinel.py i get this error

Traceback (most recent call last):
  File "bin/sentinel.py", line 265, in <module>
    main()
  File "bin/sentinel.py", line 209, in main
    sentinel_ping(dashd)
  File "bin/sentinel.py", line 73, in sentinel_ping
    dashd.ping()
  File "lib/dashd.py", line 248, in ping
    self.rpc_command('sentinelping', config.sentinel_version)
  File "lib/dashd.py", line 42, in rpc_command
    return self.rpc_connection.__getattr__(params[0])(*params[1:])
  File "/root/.Sparks/sentinel/venv/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 141, in __call__
    raise JSONRPCException(response['error'])
bitcoinrpc.authproxy.JSONRPCException: -32601: Method not found

Can you please help me fix this problem

*EDIT*
Status now ENABLED, but error is still the same. MN can not be found on masternodes.online

**Comment by StifflersMoM69** [comment]
Status changes to EXPIRED after couple of hours. Please help.
